---
- name: Add routers to in-memory inventory
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Add router1 to inventory
      add_host:
        name: router1
        ansible_host: 192.168.1.101
        ansible_user: cisco
        ansible_password: cisco
        ansible_network_os: ios
        ansible_connection: network_cli
        
- name: Run show commands on routers
  hosts: router1   # Run on the dynamically added routers
  gather_facts: no

  tasks:
    - name: Run show commands on router
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
          - show version
          - show running-config | include username
          - show inventory
          - show interfaces description
          - show processes cpu
          - sh run | sec aaa
          - sh run | sec tacacs
          - sh int | i GigabitEthernet|drop
          - sh int | i GigabitEthernet|CRC
          - sh int | i GigabitEthernet|load
          - sh spanning-tree detail | i last
          - sh int | i GigabitEthernet|speed|CRC|load|drops
          - sh inventory
          - sh running-config | i username
          - sh logging
          - show ip interface brief
      register: show_output

    - name: Display command output
      debug:
        msg: "{{ show_output.stdout_lines }}"

    - name: Save output to a file
      copy:
        content: "{{ show_output.stdout | join('\n') }}"
        dest: "./router_show_output_{{ inventory_hostname }}.txt"