- name: Monitor CPU Utilization on VMware Ubuntu VM

  hosts: localhost

  gather_facts: no
 
  tasks:

    - name: Define remote host as an inventory dynamically

      add_host:

        name: "192.168.1.25"

        groups: "remote"

        ansible_user: "qa"

        ansible_password: "ubuntu"

        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
 
- name: Run tasks on the remote Ubuntu VM

  hosts: remote

  gather_facts: yes
 
  tasks:

    - name: Get CPU usage

      command: cat /proc/stat

      register: cpu_stat
 
    - name: Display CPU Statistics

      debug:

        msg: "{{ cpu_stat.stdout_lines }}"

 